// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1XV31cyhLmN4pqud5AtGLSYdLvzIGEtc',
    appId: '1:546635603405:web:d36352a30bb09ded10f884',
    messagingSenderId: '546635603405',
    projectId: 'cafepro-manager',
    authDomain: 'cafepro-manager.firebaseapp.com',
    storageBucket: 'cafepro-manager.firebasestorage.app',
    measurementId: 'G-0JVNH9GHT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBboPtMMGTdsPeauEAJezD2D3ob4tk3W6A',
    appId: '1:546635603405:android:af2e5489c2d2143f10f884',
    messagingSenderId: '546635603405',
    projectId: 'cafepro-manager',
    storageBucket: 'cafepro-manager.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1XV31cyhLmN4pqud5AtGLSYdLvzIGEtc',
    appId: '1:546635603405:web:9d6f8801bfbe9de010f884',
    messagingSenderId: '546635603405',
    projectId: 'cafepro-manager',
    authDomain: 'cafepro-manager.firebaseapp.com',
    storageBucket: 'cafepro-manager.firebasestorage.app',
    measurementId: 'G-278WBVJZ20',
  );
}
